# Generated by Django 4.0.5 on 2022-06-26 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(default='Manager', max_length=50),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default='Manager', max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
