# Generated by Django 4.0.5 on 2022-06-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_manager_first_name_manager_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='manager',
            name='username',
            field=models.CharField(default='manager', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='player',
            name='country',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='FirstName', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='LastName', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=5000000.0, max_digits=20, verbose_name='cash in $'),
        ),
        migrations.AddField(
            model_name='team',
            name='country',
            field=models.CharField(default='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='team',
            name='team_value',
            field=models.DecimalField(decimal_places=2, default=20000000.0, max_digits=20, verbose_name='team value in $'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='first_name',
            field=models.CharField(default='name1', max_length=50),
        ),
        migrations.AlterField(
            model_name='manager',
            name='last_name',
            field=models.CharField(default='name2', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(default='TeamName', max_length=100),
        ),
    ]
