# Generated by Django 4.0.5 on 2022-06-26 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_manager_avatar_remove_player_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='manager.manager'),
        ),
    ]
