# Generated by Django 4.0.5 on 2022-06-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_team_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=5000000.0, editable=False, max_digits=20, verbose_name='cash in $'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_value',
            field=models.DecimalField(decimal_places=2, default=20000000.0, editable=False, max_digits=20, verbose_name='team value in $'),
        ),
    ]
