# Generated by Django 4.0.5 on 2022-06-26 10:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_alter_team_cash_alter_team_team_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='cash',
            field=models.DecimalField(decimal_places=2, default=5000000.0, max_digits=20, verbose_name='cash in $'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_value',
            field=models.DecimalField(decimal_places=2, default=20000000.0, max_digits=20, verbose_name='team value in $'),
        ),
    ]
