# Generated by Django 4.0.5 on 2022-06-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_player_country_alter_team_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('goal_keeper', 'Goal Keeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('attacker', 'Attacker')], default='position', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='value',
            field=models.DecimalField(decimal_places=2, default=1000000.0, max_digits=100, verbose_name='value in $'),
        ),
    ]
